services:
  # Backend API
  - type: web
    name: quick-capture-api
    runtime: node
    region: oregon
    plan: free
    branch: master
    buildCommand: npm install && npm run build --workspace=backend
    startCommand: npm run start:backend
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: quick-capture-frontend
    runtime: static
    branch: master
    buildCommand: npm install && npm run build:frontend
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: quick-capture-api
          envVarKey: RENDER_EXTERNAL_URL
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    autoDeploy: true
