export type ItemType = 'task' | 'event';
export type ItemStatus = 'Open' | 'In Progress' | 'On Hold' | 'Blocked' | 'Completed' | 'Canceled';

export interface Item {
  id: string;
  sequential_id: number;
  type: ItemType;
  title: string;
  status: ItemStatus;
  start_iso?: string | null;
  duration_min?: number | null;
  all_day?: boolean | null;
  location?: string | null;
  attendees?: string[] | null;
  due_date?: string | null;
  due_week_start?: string | null;
  effort_min?: number | null;
  deadline_type?: 'hard' | 'soft' | null;
  priority?: 1 | 2 | 3 | 4 | 5 | null;
  earliest_start?: string | null;
  recurrence?: string | null;
  subtasks?: string[] | null;
  dependencies?: string[] | null;
  tags?: string[] | null;
  notes?: string | null;
  urls?: string[] | null;
  timezone: string;
  created_at: string;
  updated_at: string;
}

export interface DbItem extends Omit<Item, 'id' | 'sequential_id' | 'status'> {
  id?: string;
  sequential_id?: number; // Auto-generated by database
  status?: ItemStatus; // Defaults to 'Open' if not provided
}
